### ISSUE TITLE
`alias_method': undefined method `insert' for class `Moped::Collection' (NameError)

### ISSUE THREAD

**Issue by cbarratt** [bnorton/moped-cleaner#1]
Rails 4.1.5
RSpec 3.0.2

Trying to run my specs I get the following error and stack trace:

```
/.rvm/gems/ruby-2.1.2/gems/activesupport-4.1.5/lib/active_support/core_ext/module/aliasing.rb:32:in `alias_method': undefined method `insert' for class `Moped::Collection' (NameError)
 .rvm/gems/ruby-2.1.2/gems/activesupport-4.1.5/lib/active_support/core_ext/module/aliasing.rb:32:in `alias_method_chain'
 .rvm/gems/ruby-2.1.2/gems/moped-cleaner-0.1.4/lib/overrides.rb:9:in `<class:Collection>'
 .rvm/gems/ruby-2.1.2/gems/moped-cleaner-0.1.4/lib/overrides.rb:2:in `<module:Moped>'
 .rvm/gems/ruby-2.1.2/gems/moped-cleaner-0.1.4/lib/overrides.rb:1:in `<top (required)>'
 .rvm/gems/ruby-2.1.2/gems/activesupport-4.1.5/lib/active_support/dependencies.rb:247:in `require'
 .rvm/gems/ruby-2.1.2/gems/activesupport-4.1.5/lib/active_support/dependencies.rb:247:in `block in require'
 .rvm/gems/ruby-2.1.2/gems/activesupport-4.1.5/lib/active_support/dependencies.rb:232:in `load_dependency'
 .rvm/gems/ruby-2.1.2/gems/activesupport-4.1.5/lib/active_support/dependencies.rb:247:in `require'
 .rvm/gems/ruby-2.1.2/gems/moped-cleaner-0.1.4/lib/moped-cleaner.rb:4:in `included'
 .rvm/gems/ruby-2.1.2/gems/rspec-core-3.0.4/lib/rspec/core/configuration.rb:1018:in `include'
 .rvm/gems/ruby-2.1.2/gems/rspec-core-3.0.4/lib/rspec/core/configuration.rb:1018:in `safe_include'
 .rvm/gems/ruby-2.1.2/gems/rspec-core-3.0.4/lib/rspec/core/configuration.rb:1012:in `block in configure_group'
 .rvm/gems/ruby-2.1.2/gems/rspec-core-3.0.4/lib/rspec/core/configuration.rb:1010:in `each'
 .rvm/gems/ruby-2.1.2/gems/rspec-core-3.0.4/lib/rspec/core/configuration.rb:1010:in `configure_group'
 .rvm/gems/ruby-2.1.2/gems/rspec-core-3.0.4/lib/rspec/core/world.rb:86:in `configure_group'
 .rvm/gems/ruby-2.1.2/gems/rspec-core-3.0.4/lib/rspec/core/example_group.rb:362:in `set_it_up'
 .rvm/gems/ruby-2.1.2/gems/rspec-core-3.0.4/lib/rspec/core/example_group.rb:329:in `subclass'
 .rvm/gems/ruby-2.1.2/gems/rspec-core-3.0.4/lib/rspec/core/example_group.rb:227:in `block in define_example_group_method'
 .rvm/gems/ruby-2.1.2/gems/rspec-core-3.0.4/lib/rspec/core/dsl.rb:41:in `block in expose_example_group_alias'
 .rvm/gems/ruby-2.1.2/gems/rspec-core-3.0.4/lib/rspec/core/dsl.rb:79:in `block (2 levels) in expose_example_group_alias_globally'
 .rvm/gems/ruby-2.1.2/gems/rspec-core-3.0.4/lib/rspec/core/configuration.rb:1058:in `load'
 .rvm/gems/ruby-2.1.2/gems/rspec-core-3.0.4/lib/rspec/core/configuration.rb:1058:in `block in load_spec_files'
 .rvm/gems/ruby-2.1.2/gems/rspec-core-3.0.4/lib/rspec/core/configuration.rb:1058:in `each'
 .rvm/gems/ruby-2.1.2/gems/rspec-core-3.0.4/lib/rspec/core/configuration.rb:1058:in `load_spec_files'
 .rvm/gems/ruby-2.1.2/gems/rspec-core-3.0.4/lib/rspec/core/runner.rb:97:in `setup'
 .rvm/gems/ruby-2.1.2/gems/rspec-core-3.0.4/lib/rspec/core/runner.rb:85:in `run'
 .rvm/gems/ruby-2.1.2/gems/rspec-core-3.0.4/lib/rspec/core/runner.rb:70:in `run'
 .rvm/gems/ruby-2.1.2/gems/rspec-core-3.0.4/lib/rspec/core/runner.rb:38:in `invoke'
 .rvm/gems/ruby-2.1.2/gems/rspec-core-3.0.4/exe/rspec:4:in `<top (required)>'
 .rvm/gems/ruby-2.1.2/bin/rspec:23:in `load'
 .rvm/gems/ruby-2.1.2/bin/rspec:23:in `<main>'
 .rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
 .rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by bnorton** [comment]
@cbarratt Can you add your gemfile or information on your mongoid and moped versions?

**Comment by cbarratt** [comment]
Ignore this issue! Got it working :)

**Comment by bnorton** [comment]
@cbarratt If you have time, add your findings to (https://github.com/bnorton/moped-cleaner/wiki/Performance-Results)
